#!/bin/sh

#DEBHELPER#

set -eu

BASE=/usr/share/bananas

case "${1}" in
	configure)
		gunicorn-debian stop bananas
		su www-data -c "${BASE}/bananas/manage.py migrate --all --noinput"
		ln -sf ${BASE}/config/gunicorn /etc/gunicorn.d/bananas
		gunicorn-debian start bananas

		ln -sf ${BASE}/config/nginx /etc/nginx/sites-enabled/bananas
		invoke-rc.d nginx reload
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

exit 0
