#!/bin/sh

#DEBHELPER#

set -eu

BASE=/usr/share/bananas

case "${1}" in
	configure)
		gunicorn-debian stop bananas || true
		su www-data -c "${BASE}/bananas/manage.py migrate --all --noinput"
		gunicorn-debian start bananas || true
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

exit 0
